#config
configfile: "config.yaml"

rule all:
    input:
        "md/md.gro",
        "md/md.xtc",
        "md/em.gro",
        "md/nvt.gro",
        "md/npt.gro",
        "md/index.ndx",
        "md/posres_LIG.itp"

rule prep_protein:
    input:
        config["protein_file"]
    output:
        gro="md/protein.gro",
        top="md/topol.top",
        itp="md/posre.itp"
    shell:
        """
        mkdir -p md
        echo 15 | gmx pdb2gmx -f {input} -o {output.gro} -p {output.top} -i {output.itp} -ignh -water spc
        sed -i 's|"md/posre.itp"|"posre.itp"|g' {output.top}
        """
rule prep_ligand1:
    input:
        config["ligand1_file"]
    output:
        itp="md/ligand1.itp",
        gro="md/ligand1.gro",
    shell:
        """
        cd md
        mkdir -p LIG1
        cd LIG1
        cp {input} .
        antechamber -i {input} -fi pdb -o ligand1.mol2 -fo mol2 -c bcc -s 2
        parmchk2 -i ligand1.mol2 -f mol2 -o ligand1.frcmod
        
        """